# name: Generate Snake
# on:
#   schedule:
#     - cron: "0 */12 * * *"
#   workflow_dispatch:
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#       - name: Generate snake
#         uses: Platane/snk@v3
#         with:
#           github_user_name: Mbuguamaureen01
#           outputs: dist/snake.svg
#           args: >
#             --background '#000000'
#             --color_snake '#39d353'
#             --color_dots '#000000,#39d353,#39d353,#39d353,#39d353'
#       - name: Deploy to output branch
#         uses: crazy-max/ghaction-github-pages@v3
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
